name: hook responder

on: [repository_dispatch]

jobs:
  response-hook:
    runs-on: ubuntu-latest
    steps:
      - name: event info
        run: |
          echo "updated '${{ github.event.client_payload.repository }}'@'${{ github.event.client_payload.version }}'"
      - name: response to received hook
        if: github.event.action == 'hook'
        - uses: actions/checkout@v2
        - name: create report file
          run: date +%s > report.txt
        - name: create Pull Request
           id: cpr
           uses: peter-evans/create-pull-request@v2
           with:
            token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
            commit-message: chore: add report file
            committer: tak <tak-bro@users.noreply.github.com>
            author: tak <tak-bro@users.noreply.github.com>
            title: '[Test] add report file'
            body: |
              New report
              - Contains *today's* date
            labels: report, automated pr
            assignees: tak-bro
            reviewers: tak-bro
            team-reviewers: owners, maintainers
            branch: master
        - name: check outputs
           run: |
             echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
             echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
